### ISSUE TITLE
Add an happy path goth integration test

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/dapp-runner#39]
As for now there are not integration tests in `dapp-runner` and therefore we cannot ensure that new changes are not introducing bugs
therefore, we would like to have basic set of integration tests added to the project.

---

### ToDo

- [x] analogous to what we have in yapapi, add an goth-based framework
- [x] add test case which will run the most "basic hello word" dapp
  - [x] node went through all expected states (pending, starting, running, terminated)
  - [ ] expected `hello world` message was properly generated and returned by the node
- [x] add test case which will run dapp consistent of at least two nodes with `depends_on` dependency
- [x] CI setup that will run the test for every PR
