### ISSUE TITLE
extend dApp runner GAOM support

### ISSUE THREAD

**Issue by lucekdudek** [golemfactory/dapp-runner#97]
* [x] https://github.com/golemfactory/dapp-runner/issues/101
* [x] add a GAOM API server to enable querying and - in the future - updates to the GAOM
    * [x] POC of an API server
    * [x] first proper implementation of the GAOM API
* [x] unified querying mechanism
    * [x] specify a mechanism able to access any properties within the GAOM
    * [x] implement the querying mechanism
* [x] App descriptor interpolation
    * [x] specify the App descriptor syntax to access GAOM properties
    * [x] implement App descriptor interpolation of GAOM properties
* [x] GAOM examples
    * [x] IP address specification using a property from another node
    * [x] querying an internal property
